# Databricks notebook source
# MAGIC %sql
# MAGIC drop table if exists gold.dsd_pr_fbfg ;
# MAGIC create table gold.dsd_pr_fbfg
# MAGIC 
# MAGIC (
# MAGIC MANDT STRING,
# MAGIC PRONR STRING,
# MAGIC SEQNR STRING,
# MAGIC VBELN STRING,
# MAGIC POSNR STRING,
# MAGIC DOC_TYPE STRING,
# MAGIC TOUR_ID STRING,
# MAGIC MATNR STRING,
# MAGIC ZMENG STRING,
# MAGIC ZIEME STRING,
# MAGIC VBELN_INT STRING,
# MAGIC POSNR_INT STRING,
# MAGIC EMSE_DC_FLAG STRING,
# MAGIC 
# MAGIC CREATE_AT TIMESTAMP,
# MAGIC YEAR_MONTH_DAY STRING,
# MAGIC ORIGIN_FILE STRING
# MAGIC )
# MAGIC using delta
# MAGIC partitioned by (YEAR_MONTH_DAY)
# MAGIC LOCATION '/mnt/data_s4/gold/dsd_pr_fbfg'
