# Databricks notebook source
# MAGIC %sql
# MAGIC drop table if exists silver.facturacion_detalle ;
# MAGIC create table silver.facturacion_detalle
# MAGIC (
# MAGIC cod_factura	string,
# MAGIC num_posicion_factura	decimal(22,3),
# MAGIC cod_unidad_medida_venta	string,
# MAGIC cod_unidad_medida_base	string,
# MAGIC ctd_factura_unidades_medida_entrega	decimal(22,3),
# MAGIC num_peso_neto	decimal(22,3),
# MAGIC num_peso_bruto	decimal(22,3),
# MAGIC num_volumen	decimal(22,3),
# MAGIC mto_neto_detalle	decimal(22,3),
# MAGIC num_documento_modelo	decimal(22,3),
# MAGIC num_posicion_modelo	decimal(22,3),
# MAGIC num_documento_venta	decimal(22,3),
# MAGIC cod_producto	string,
# MAGIC num_lote	decimal(22,3),
# MAGIC cod_grupo_producto	string,
# MAGIC cod_tipo_posicion	string,
# MAGIC cod_jerarquia_producto	string,
# MAGIC cod_punto_expedicion_producto	string,
# MAGIC cod_centro	string,
# MAGIC cod_grupo_vendedores	string,
# MAGIC cod_oficina_ventas	string,
# MAGIC cod_almacen	string,
# MAGIC mto_costo_interno	decimal(22,3),
# MAGIC mto_subtotal1_esquema_calculo	decimal(22,3),
# MAGIC mto_subtotal2_esquema_calculo	decimal(22,3),
# MAGIC mto_subtotal3_esquema_calculo	decimal(22,3),
# MAGIC mto_subtotal4_esquema_calculo	decimal(22,3),
# MAGIC mto_subtotal5_esquema_calculo	decimal(22,3),
# MAGIC mto_subtotal6_esquema_calculo	decimal(22,3),
# MAGIC cod_grupo_clientes_1	string,
# MAGIC cod_grupo_clientes_2	string,
# MAGIC cod_grupo_clientes_3	string,
# MAGIC cod_grupo_clientes_4	string,
# MAGIC cod_grupo_clientes_5	string,
# MAGIC cod_grupo_material_1	string,
# MAGIC cod_grupo_material_2	string,
# MAGIC cod_grupo_material_3	string,
# MAGIC cod_grupo_material_4	string,
# MAGIC cod_grupo_material_5	string,
# MAGIC mto_impuesto_documento	decimal(22,3),
# MAGIC cod_motivo_pedido	string,
# MAGIC cod_grupo_condiciones_cliente_1	string,
# MAGIC cod_territorio	string,
# MAGIC fec_creacion	date,
# MAGIC fec_modificacion	date,
# MAGIC cod_sistema_origen	string,
# MAGIC year_month_day string
# MAGIC )
# MAGIC using delta
# MAGIC partitioned by (year_month_day)
# MAGIC LOCATION '/mnt/data_entities/silver/facturacion_detalle'
