# Databricks notebook source
# MAGIC %sql
# MAGIC drop table if exists bronze.tactics ;
# MAGIC create table bronze.tactics
# MAGIC (
# MAGIC CRM_MKTELM STRING
# MAGIC ,CRM_TACTIC STRING
# MAGIC ,CRM_OBJEC4 STRING
# MAGIC ,CRM_PLGRP STRING
# MAGIC ,CRMCAMPTYP STRING
# MAGIC ,BUY_DATF STRING
# MAGIC ,BUY_DATT STRING
# MAGIC ,STAMKTSYS0 STRING
# MAGIC ,STAMKTSYS1 STRING
# MAGIC ,STAMKTSYS2 STRING
# MAGIC ,STAMKTSYS3 STRING
# MAGIC ,BP_GRP_SRC STRING
# MAGIC ,CUSTOMER STRING
# MAGIC ,BPARTNER STRING
# MAGIC ,CRM_SALORG STRING
# MAGIC ,DISTR_CHAN STRING
# MAGIC ,DIVISION STRING
# MAGIC ,TXTLG STRING
# MAGIC 
# MAGIC ,CREATE_AT timestamp
# MAGIC ,YEAR_MONTH_DAY string
# MAGIC ,ORIGIN_FILE string
# MAGIC )
# MAGIC using delta
# MAGIC partitioned by (YEAR_MONTH_DAY)
# MAGIC LOCATION '/mnt/data_bwtpm/bronze/tactics'
# MAGIC     
