# Databricks notebook source
# MAGIC %sql
# MAGIC drop table if exists gold.zsd_tgrpma00 ;
# MAGIC create table gold.zsd_tgrpma00
# MAGIC (
# MAGIC MANDT STRING,
# MAGIC ZSD_CENTOR STRING,
# MAGIC ZSD_CGRPMA STRING,
# MAGIC ZSD_NCORRE INT,
# MAGIC ZSD_TIPPRO STRING,
# MAGIC ZSD_CCATEG INT,
# MAGIC ZSD_CMARCA STRING,
# MAGIC ZSD_CFAMMT INT,
# MAGIC ZSD_CVARIE STRING,
# MAGIC ZSD_CLINEA STRING,
# MAGIC ZSD_CSGMAT STRING,
# MAGIC ZSD_CJERAR STRING,
# MAGIC ZSD_CMATER INT,
# MAGIC ZSD_QCONGR DECIMAL(22,3),
# MAGIC ZSD_CUNMED STRING,
# MAGIC ZSD_TIPOUM STRING,
# MAGIC ZSD_LINCLU STRING,
# MAGIC ZSD_DUSCRE STRING,
# MAGIC ZSD_FCREAC INT,
# MAGIC ZSD_DUSMOD STRING,
# MAGIC ZSD_FMODIF INT,
# MAGIC ZSD_LACUM STRING,
# MAGIC ZSD_PACUM STRING,
# MAGIC ZSD_UNACUM STRING,
# MAGIC ZSD_DFRASE STRING,
# MAGIC ZSD_DLETRA STRING,
# MAGIC ZSD_BUKRS STRING,
# MAGIC ZSD_ZFLAGM STRING,
# MAGIC ZSD_FCLAIN INT,
# MAGIC ZSD_FFORCL INT,
# MAGIC ZSD_MINXCO DECIMAL(22,3),
# MAGIC ZSD_QXMATE INT,
# MAGIC ZSD_MINCOB DECIMAL(22,3),
# MAGIC ZSD_UNICOB STRING,
# MAGIC ZSD_CGRMAT STRING,
# MAGIC ZSD_CLINS4 STRING,
# MAGIC ZCPLATS4 STRING,
# MAGIC ZCSPLATS4 STRING,
# MAGIC ZSD_CPACK STRING,
# MAGIC ZSD_LATRM STRING,
# MAGIC 
# MAGIC 
# MAGIC CREATE_AT timestamp,
# MAGIC YEAR_MONTH_DAY string,
# MAGIC ORIGIN_FILE string
# MAGIC )
# MAGIC using delta
# MAGIC partitioned by (YEAR_MONTH_DAY)
# MAGIC LOCATION '/mnt/data_sx/gold/zsd_tgrpma00'
# MAGIC     
