-- Databricks notebook source
-- MAGIC %sql
-- MAGIC drop table if exists bronze.tmkm1t ;
-- MAGIC create table bronze.tmkm1t
-- MAGIC (
-- MAGIC mandt string ,
-- MAGIC spras string ,
-- MAGIC land1 string ,
-- MAGIC taxim string ,
-- MAGIC taxib string ,
-- MAGIC create_at timestamp ,
-- MAGIC origin_file string ,
-- MAGIC year_month_day string 
-- MAGIC )
-- MAGIC using delta
-- MAGIC partitioned by (YEAR_MONTH_DAY)
-- MAGIC LOCATION '/mnt/data_s4/bronze/tmkm1t'
-- MAGIC     
