-- Databricks notebook source
-- MAGIC %sql
-- MAGIC drop table if exists datagov.resumen_control_stg ;
-- MAGIC create table datagov.resumen_control_stg 
-- MAGIC (
-- MAGIC    frente string,
-- MAGIC    fecha_proceso date,
-- MAGIC    id_control string,
-- MAGIC    cod_sociedad string,
-- MAGIC    filtro1 string,
-- MAGIC    filtro2 string,
-- MAGIC    filtro3 string,
-- MAGIC    regs_ok int,
-- MAGIC    regs_total int
-- MAGIC )
-- MAGIC using delta
-- MAGIC partitioned by (frente)
-- MAGIC 
-- MAGIC LOCATION '/mnt/data_governance/calidad-de-datos/data/resumen_control_stg'
