# Databricks notebook source
# MAGIC %sql
# MAGIC drop table if exists silver.zsd_a974 ;
# MAGIC create table silver.zsd_a974
# MAGIC (
# MAGIC MANDT STRING,
# MAGIC ZSD_CAPLIC STRING,
# MAGIC ZSD_CCLCON STRING,
# MAGIC ZSD_CSOCIE STRING,
# MAGIC ZSD_CCADIS STRING,
# MAGIC ZSD_COFVTA STRING,
# MAGIC ZSD_CGRMAS4 STRING,
# MAGIC ZSD_GRPREC STRING,
# MAGIC ZSD_CFAMMT STRING,
# MAGIC ZSD_FFINVA STRING,
# MAGIC ZSD_FINIVA STRING,
# MAGIC ZSD_CCENTR STRING,
# MAGIC ZSD_CRECON STRING,
# MAGIC 
# MAGIC CREATE_AT timestamp,
# MAGIC YEAR_MONTH_DAY string,
# MAGIC ORIGIN_FILE string
# MAGIC )
# MAGIC using delta
# MAGIC partitioned by (YEAR_MONTH_DAY)
# MAGIC LOCATION '/mnt/data_sx/silver/zsd_a974'
# MAGIC     
