# Databricks notebook source
import json 

def conf_json ():
    json_file = '''
    [
        { "name": "KNA1","partition_field": "d"},
        { "name": "KNVH","partition_field": "d"},
        { "name": "KNVV","partition_field": "d"},
        { "name": "KNB1","partition_field": "d"},
        { "name": "LIPS","partition_field": "d"},
        { "name": "LIKP","partition_field": "d"},
        { "name": "VBAP","partition_field": "d"},
        { "name": "VBAK","partition_field": "d"},
        { "name": "MARA","partition_field": "d"},
        { "name": "MAKT","partition_field": "d"},
        { "name": "T179","partition_field": "d"},
        { "name": "T179T","partition_field": "d"},
        { "name": "MARM","partition_field": "d"},
        { "name": "MVKE","partition_field": "d"},
        { "name": "VBRP","partition_field": "d"},
        { "name": "VBRK","partition_field": "d"},
        { "name": "VTTP","partition_field": "d"},
        { "name": "VTTK","partition_field": "d"},
        { "name": "TVFKT","partition_field": "m"},
        { "name": "TVKOT","partition_field": "m"},
        { "name": "TVTWT","partition_field": "m"},
        { "name": "TVSBT","partition_field": "x"},
        { "name": "T188T","partition_field": "x"},
        { "name": "T151T","partition_field": "x"},
        { "name": "T171T","partition_field": "x"},
        { "name": "T189T","partition_field": "x"},
        { "name": "T052U","partition_field": "m"},
        { "name": "TVKTT","partition_field": "x"},
        { "name": "T005T","partition_field": "m"},
        { "name": "T005U","partition_field": "m"},
        { "name": "TCURT","partition_field": "m"},
        { "name": "TSPAT","partition_field": "m"},
        { "name": "T014T","partition_field": "m"},    
        { "name": "TVAST","partition_field": "m"},
        { "name": "T077X","partition_field": "m"},
        { "name": "TZONT","partition_field": "m"},
        { "name": "T006A","partition_field": "x"},
        { "name": "T023T","partition_field": "m"},
        { "name": "TVAPT","partition_field": "m"},
        { "name": "TVSTT","partition_field": "m"},
        { "name": "TVKMT","partition_field": "x"},
        { "name": "TVGRT","partition_field": "x"},
        { "name": "TVKBT","partition_field": "x"},
        { "name": "TVV4T","partition_field": "m"},
        { "name": "TVM1T","partition_field": "x"},
        { "name": "TVM2T","partition_field": "x"},
        { "name": "TVM4T","partition_field": "x"},
        { "name": "TVKGGT","partition_field": "m"},
        { "name": "BKPF","partition_field": "d"},
        { "name": "ACDOCA","partition_field": "d"},
        { "name": "WBRK","partition_field": "d"},
        { "name": "T001","partition_field": "x"},
        { "name": "T134T","partition_field": "x"},
        { "name": "T001K","partition_field": "x"},
        { "name": "T001W","partition_field": "x"},
        { "name": "KNVP", "partition_field": "d"},
        { "name": "MARC","partition_field": "d"},
        { "name": "MARD","partition_field": "d"},
        { "name": "MBEW","partition_field": "d"},
        { "name": "TVKO","partition_field": "x"},
        { "name": "MKAL","partition_field": "d"},
        { "name": "MAST","partition_field": "d"},
        { "name": "STKO","partition_field": "d"},
        { "name": "STAS","partition_field": "d"},
        { "name": "T141T","partition_field": "x"},
        { "name": "T438T","partition_field": "x"},
        { "name": "T024D","partition_field": "x"},
        { "name": "T460T","partition_field": "x"},
        { "name": "TLGRT","partition_field": "x"},
        { "name": "T025T","partition_field": "x"},
        { "name": "TMKM1T","partition_field": "x"},
        { "name": "MLAN","partition_field": "d"},
        { "name": "T460A","partition_field": "m"},
        { "name": "T024","partition_field": "x"},
        { "name": "T001L","partition_field": "x"},
        { "name": "ZTOTC_COSTPREC","partition_field": "d"},
        { "name": "TVMST","partition_field": "x"},
        { "name": "BUT000","partition_field": "d"},
        { "name": "TB002","partition_field": "x"},
        { "name": "LFA1","partition_field": "d"},
        { "name": "ADRC","partition_field": "d"},
        { "name": "STPO","partition_field": "d"},
        { "name": "TTGRT","partition_field": "x"},
        { "name": "PRDKZT","partition_field": "x"},
        { "name": "T024X","partition_field": "x"},
        { "name": "PRCD_ELEMENTS","partition_field": "d"},
        { "name": "EMSE_DC_SCALES","partition_field": "d"},
        { "name": "DSD_PR_FBFG","partition_field": "d"},
        { "name": "DSD_PR_FBAM","partition_field": "d"},
        { "name": "A901","partition_field": "d"},
        { "name": "A913","partition_field": "d"},
        { "name": "A945","partition_field": "d"},
        { "name": "A956","partition_field": "d"},
        { "name": "A984","partition_field": "d"},
        { "name": "KONH","partition_field": "d"},
        { "name": "KONP","partition_field": "d"},
        { "name": "MCHA","partition_field": "d"},
        { "name": "MCHB","partition_field": "d"},
        { "name": "MCH1","partition_field": "d"},
        { "name": "DFKKBPTAXNUM","partition_field": "d"},
        { "name": "ADR2","partition_field": "d"},
        { "name": "ADR6","partition_field": "d"},
        { "name": "ADRT","partition_field": "d"},
        { "name": "BUT100","partition_field": "d"},
        { "name": "KNVI","partition_field": "d"},
        { "name": "EKKO","partition_field": "d"},
        { "name": "EKPO","partition_field": "d"}
    ]
    '''
    list_table = json.loads(json_file)
    return list_table


print("****** conf_json  *********")
