# Databricks notebook source
# MAGIC %sql
# MAGIC drop table if exists bronze.zsd_pdtdcc00 ;
# MAGIC create table bronze.zsd_pdtdcc00
# MAGIC (
# MAGIC MANDT STRING
# MAGIC ,ZSD_NDFACT STRING
# MAGIC ,ZSD_NPOSIC STRING
# MAGIC ,ZSD_CCLPOS STRING
# MAGIC ,ZSD_SPOSIC STRING
# MAGIC ,ZSD_CMOTIV STRING
# MAGIC ,ZSD_CMATER STRING
# MAGIC ,ZSD_QMATER STRING
# MAGIC ,ZSD_CUNMED STRING
# MAGIC ,ZSD_QLIQVT STRING
# MAGIC ,ZSD_QLIQBA STRING
# MAGIC ,ZSD_QDEBAS STRING
# MAGIC ,ZSD_RPERCE STRING
# MAGIC ,ZSD_IUNITA STRING
# MAGIC ,ZSD_IDCTUN STRING
# MAGIC ,ZSD_IRECUN STRING
# MAGIC ,ZSD_IBRUTO STRING
# MAGIC ,ZSD_IDESCT STRING
# MAGIC ,ZSD_IRECAR STRING
# MAGIC ,ZSD_IIMPUE STRING
# MAGIC ,ZSD_INETO STRING
# MAGIC ,ZSD_INEACT STRING
# MAGIC ,ZSD_TTAX1 STRING
# MAGIC ,ZSD_VTAX1 STRING
# MAGIC ,ZSD_TTAX2 STRING
# MAGIC ,ZSD_VTAX2 STRING
# MAGIC ,ZSD_TTAX3 STRING
# MAGIC ,ZSD_VTAX3 STRING
# MAGIC ,ZSD_TTAX4 STRING
# MAGIC ,ZSD_VTAX4 STRING
# MAGIC ,ZSD_TTAX5 STRING
# MAGIC ,ZSD_VTAX5 STRING
# MAGIC ,ZSD_TTAX6 STRING
# MAGIC ,ZSD_VTAX6 STRING
# MAGIC ,ZSD_TTAX7 STRING
# MAGIC ,ZSD_VTAX7 STRING
# MAGIC ,ZSD_TTAX8 STRING
# MAGIC ,ZSD_VTAX8 STRING
# MAGIC ,ZSD_TTAX9 STRING
# MAGIC ,ZSD_VTAX9 STRING
# MAGIC ,ZSD_CMONED STRING
# MAGIC ,ZSD_IUNIML STRING
# MAGIC ,ZSD_IBRUML STRING
# MAGIC ,ZSD_IDSCML STRING
# MAGIC ,ZSD_IRECML STRING
# MAGIC ,ZSD_IIMPML STRING
# MAGIC ,ZSD_INETML STRING
# MAGIC ,ZSD_CMONLO STRING
# MAGIC ,ZSD_PBRUTO STRING
# MAGIC ,ZSD_PNETO STRING
# MAGIC ,ZSD_CUNMPE STRING
# MAGIC ,ZSD_VENTTO STRING
# MAGIC ,ZSD_CUNMVO STRING
# MAGIC ,ZSD_NPOSOR STRING
# MAGIC ,ZSD_CPROMO STRING
# MAGIC ,ZSD_CENTRE STRING
# MAGIC ,ZSD_CNEGOC STRING
# MAGIC ,ZSD_LPROMT STRING
# MAGIC ,ZSD_CPEDTG STRING
# MAGIC ,ZSD_CPEDID STRING
# MAGIC ,ZSD_IDESPD STRING
# MAGIC ,ZSD_QMATAV STRING
# MAGIC ,ZSD_CUNMAV STRING
# MAGIC ,ZSD_FPRDSG STRING
# MAGIC ,ZSD_IMARGEN STRING
# MAGIC ,ZSD_DEPOALIC STRING
# MAGIC ,ZSD_IBRUFE STRING
# MAGIC ,ZSD_IDSCFE STRING
# MAGIC ,ZSD_IRECFE STRING
# MAGIC ,ZSD_IIMPFE STRING
# MAGIC ,ZSD_INETFE STRING
# MAGIC ,ZSD_INACFE STRING
# MAGIC 
# MAGIC ,CREATE_AT timestamp
# MAGIC ,YEAR_MONTH_DAY string
# MAGIC ,ORIGIN_FILE string
# MAGIC )
# MAGIC using delta
# MAGIC partitioned by (YEAR_MONTH_DAY)
# MAGIC LOCATION '/mnt/data_sx/bronze/zsd_pdtdcc00'
# MAGIC     
