# Databricks notebook source
# MAGIC %sql
# MAGIC drop table if exists bronze.zsd_tgener00 ;
# MAGIC create table bronze.zsd_tgener00
# MAGIC (
# MAGIC MANDT STRING,
# MAGIC ZSD_CTABLA STRING,
# MAGIC ZSD_CLLAVE STRING,
# MAGIC ZSD_DCORTA STRING,
# MAGIC ZSD_DLARGA STRING,
# MAGIC ZSD_SITEM STRING,
# MAGIC ZSD_NDISCR STRING,
# MAGIC ZSD_LEDITA STRING,
# MAGIC ZSD_LVALDF STRING,
# MAGIC ZSD_LCOMOD STRING,
# MAGIC ZSD_DORIGE STRING,
# MAGIC ZSD_DUSCRE STRING,
# MAGIC ZSD_FCREAC STRING,
# MAGIC ZSD_DMODIF STRING,
# MAGIC ZSD_FMODIF STRING,
# MAGIC 
# MAGIC 
# MAGIC CREATE_AT timestamp,
# MAGIC YEAR_MONTH_DAY string,
# MAGIC ORIGIN_FILE string
# MAGIC )
# MAGIC using delta
# MAGIC partitioned by (YEAR_MONTH_DAY)
# MAGIC LOCATION '/mnt/data_sx/bronze/zsd_tgener00'
# MAGIC     
