# Databricks notebook source
# MAGIC %sql
# MAGIC drop table if exists bronze.zsd_tclxpr00 ;
# MAGIC create table bronze.zsd_tclxpr00
# MAGIC (
# MAGIC MANDT STRING,
# MAGIC ZSD_CENTOR STRING,
# MAGIC ZSD_CPROMO STRING,
# MAGIC ZSD_CSOCIE STRING,
# MAGIC ZSD_CSEDE STRING,
# MAGIC ZSD_CGRPCL STRING,
# MAGIC ZSD_NRANGO STRING,
# MAGIC ZSD_FVIGIN STRING,
# MAGIC ZSD_FVIGFI STRING,
# MAGIC ZSD_LSTOCK STRING,
# MAGIC ZSD_LACUMU STRING,
# MAGIC ZSD_NMXCLI STRING,
# MAGIC ZSD_NMXTOT STRING,
# MAGIC ZSD_QENTRE STRING,
# MAGIC ZSD_DUSCRE STRING,
# MAGIC ZSD_FCREAC STRING,
# MAGIC ZSD_DUSMOD STRING,
# MAGIC ZSD_FMODIF STRING,
# MAGIC ZSD_ZFLAGM STRING,
# MAGIC ZSD_MASCLI STRING,
# MAGIC ZSD_BLOQUEO STRING,
# MAGIC 
# MAGIC CREATE_AT TIMESTAMP,
# MAGIC YEAR_MONTH_DAY STRING,
# MAGIC ORIGIN_FILE STRING
# MAGIC )
# MAGIC using delta
# MAGIC partitioned by (YEAR_MONTH_DAY)
# MAGIC LOCATION '/mnt/data_sx/bronze/zsd_tclxpr00'
