-- Databricks notebook source
-- MAGIC %sql
-- MAGIC drop table if exists datagov.fact_calidad_datos ;
-- MAGIC create table datagov.fact_calidad_datos
-- MAGIC (
-- MAGIC    fecha date,
-- MAGIC    id_control string,
-- MAGIC    cod_sociedad string,
-- MAGIC    filtro1 string,
-- MAGIC    filtro2 string,
-- MAGIC    filtro3 string,
-- MAGIC    regs_ok int,
-- MAGIC    regs_total int
-- MAGIC )
-- MAGIC using delta
-- MAGIC partitioned by (fecha)
-- MAGIC 
-- MAGIC LOCATION '/mnt/data_governance/calidad-de-datos/data/fact_calidad_datos'
