# Databricks notebook source
# MAGIC %sql
# MAGIC drop table if exists bronze.iview ; 
# MAGIC create table bronze.iview
# MAGIC (
# MAGIC FECHAS DATE,
# MAGIC CANAL STRING,
# MAGIC CADENA STRING,
# MAGIC SUB_CADENA STRING,
# MAGIC DEPARTAMENTO STRING,
# MAGIC DISTRITO STRING,
# MAGIC LOCAL STRING,
# MAGIC CLUSTER STRING,
# MAGIC CODIGO_LOCAL_ALICORP STRING,
# MAGIC LOCAL_ALICORP STRING,
# MAGIC CATEGORIA STRING,
# MAGIC FAMILIA STRING,
# MAGIC MARCA STRING,
# MAGIC VARIEDAD STRING,
# MAGIC FORMATO STRING,
# MAGIC CODIGO_DE_PRODUCTO STRING,
# MAGIC MATERIAL STRING,
# MAGIC SUBNEGOCIO STRING,
# MAGIC DUENO_MARCA STRING,
# MAGIC EAN13 STRING,
# MAGIC COD_CADENA STRING,
# MAGIC UNIDADES_B2B STRING,
# MAGIC VALORES_COSTO_B2B STRING,
# MAGIC PESO_EN_TONELADAS STRING,
# MAGIC VALORES_VENTA_B2B STRING,
# MAGIC VENTAS_SIN_IGV STRING,
# MAGIC FACTOR_DE_CONVERSION STRING,
# MAGIC PRECIOS_B2B STRING,
# MAGIC CODIGO_SAP_LOCAL STRING,
# MAGIC CREATE_AT timestamp,
# MAGIC YEAR_MONTH_DAY string,
# MAGIC ORIGIN_FILE string
# MAGIC )
# MAGIC using delta
# MAGIC partitioned by (YEAR_MONTH_DAY)
# MAGIC location '/mnt/data_iview/bronze/iview'
