# Databricks notebook source
# MAGIC %sql
# MAGIC drop table if exists bronze.mard ;
# MAGIC create table bronze.mard
# MAGIC (
# MAGIC mandt string ,
# MAGIC matnr string ,
# MAGIC werks string ,
# MAGIC lgort string ,
# MAGIC pstat string ,
# MAGIC lvorm string ,
# MAGIC lfgja string ,
# MAGIC lfmon string ,
# MAGIC sperr string ,
# MAGIC labst string ,
# MAGIC umlme string ,
# MAGIC insme string ,
# MAGIC einme string ,
# MAGIC speme string ,
# MAGIC retme string ,
# MAGIC vmlab string ,
# MAGIC vmuml string ,
# MAGIC vmins string ,
# MAGIC vmein string ,
# MAGIC vmspe string ,
# MAGIC vmret string ,
# MAGIC kzill string ,
# MAGIC kzilq string ,
# MAGIC kzile string ,
# MAGIC kzils string ,
# MAGIC kzvll string ,
# MAGIC kzvlq string ,
# MAGIC kzvle string ,
# MAGIC kzvls string ,
# MAGIC diskz string ,
# MAGIC lsobs string ,
# MAGIC lminb string ,
# MAGIC lbstf string ,
# MAGIC herkl string ,
# MAGIC exppg string ,
# MAGIC exver string ,
# MAGIC lgpbe string ,
# MAGIC klabs string ,
# MAGIC kinsm string ,
# MAGIC keinm string ,
# MAGIC kspem string ,
# MAGIC dlinl string ,
# MAGIC prctl string ,
# MAGIC ersda string ,
# MAGIC vklab string ,
# MAGIC vkuml string ,
# MAGIC lwmkb string ,
# MAGIC bskrf string ,
# MAGIC mdrue string ,
# MAGIC mdjin string ,
# MAGIC dummy_stl_incl_eew_ps string ,
# MAGIC fsh_salloc_qty_s string ,
# MAGIC cwm_labst string ,
# MAGIC cwm_insme string ,
# MAGIC cwm_einme string ,
# MAGIC cwm_speme string ,
# MAGIC cwm_retme string ,
# MAGIC cwm_umlme string ,
# MAGIC cwm_klabs string ,
# MAGIC cwm_kinsm string ,
# MAGIC cwm_keinm string ,
# MAGIC cwm_kspem string ,
# MAGIC cwm_vmlab string ,
# MAGIC cwm_vmins string ,
# MAGIC cwm_vmein string ,
# MAGIC cwm_vmspe string ,
# MAGIC cwm_vmret string ,
# MAGIC cwm_vmuml string ,
# MAGIC create_at timestamp ,
# MAGIC origin_file string ,
# MAGIC year_month_day string 
# MAGIC )
# MAGIC using delta
# MAGIC partitioned by (year_month_day)
# MAGIC LOCATION '/mnt/data_s4/bronze/mard'
# MAGIC     
