-- Databricks notebook source
-- MAGIC %sql
-- MAGIC drop table if exists bronze.eina ;
-- MAGIC create table bronze.eina
-- MAGIC (
-- MAGIC mandt string,
-- MAGIC infnr string,
-- MAGIC matnr string,
-- MAGIC matkl string,
-- MAGIC lifnr string,
-- MAGIC loekz string,
-- MAGIC erdat string,
-- MAGIC ernam string,
-- MAGIC txz01 string,
-- MAGIC sortl string,
-- MAGIC meins string,
-- MAGIC umrez string,
-- MAGIC umren string,
-- MAGIC idnlf string,
-- MAGIC verkf string,
-- MAGIC telf1 string,
-- MAGIC mahn1 string,
-- MAGIC mahn2 string,
-- MAGIC mahn3 string,
-- MAGIC urznr string,
-- MAGIC urzdt string,
-- MAGIC urzla string,
-- MAGIC urztp string,
-- MAGIC urzzt string,
-- MAGIC lmein string,
-- MAGIC regio string,
-- MAGIC vabme string,
-- MAGIC ltsnr string,
-- MAGIC ltssf string,
-- MAGIC wglif string,
-- MAGIC rueck string,
-- MAGIC lifab string,
-- MAGIC lifbi string,
-- MAGIC kolif string,
-- MAGIC anzpu string,
-- MAGIC punei string,
-- MAGIC relif string,
-- MAGIC mfrnr string,
-- MAGIC dummy_eina_incl_eew_ps string,
-- MAGIC lastchangedatetime string,
-- MAGIC iseopblocked string,
-- MAGIC create_at timestamp ,
-- MAGIC origin_file string ,
-- MAGIC year_month_day string 
-- MAGIC )
-- MAGIC using delta
-- MAGIC partitioned by (year_month_day)
-- MAGIC LOCATION '/mnt/data_s4/bronze/eina'
