# Databricks notebook source
# MAGIC %sql
# MAGIC drop table if exists gold.prcd_elements ;
# MAGIC create table gold.prcd_elements
# MAGIC (
# MAGIC client string ,
# MAGIC knumv string ,
# MAGIC kposn string ,
# MAGIC stunr string ,
# MAGIC zaehk string ,
# MAGIC kappl string ,
# MAGIC kschl string ,
# MAGIC kdatu string ,
# MAGIC krech string ,
# MAGIC kawrt decimal(22,3),
# MAGIC kbetr decimal(22,3),
# MAGIC waers string ,
# MAGIC kkurs decimal(22,3),
# MAGIC kpein string ,
# MAGIC kmein string ,
# MAGIC kumza string ,
# MAGIC kumne string ,
# MAGIC kntyp string ,
# MAGIC kstat string ,
# MAGIC knprs string ,
# MAGIC kruek string ,
# MAGIC kreli string ,
# MAGIC kherk string ,
# MAGIC kgrpe string ,
# MAGIC kolnr string ,
# MAGIC knumh string ,
# MAGIC kopos string ,
# MAGIC kvsl1 string ,
# MAGIC sakn1 string ,
# MAGIC mwsk1 string ,
# MAGIC kvsl2 string ,
# MAGIC sakn2 string ,
# MAGIC mwsk2 string ,
# MAGIC lifnr string ,
# MAGIC kdiff decimal(22,3),
# MAGIC kwert decimal(22,3),
# MAGIC waerk string ,
# MAGIC ksteu string ,
# MAGIC kinak string ,
# MAGIC koaid string ,
# MAGIC zaeko string ,
# MAGIC kfaktor string ,
# MAGIC kdupl string ,
# MAGIC kfaktor1 string ,
# MAGIC kzbzg decimal(22,3),
# MAGIC kstbs decimal(22,3),
# MAGIC konms string ,
# MAGIC konws string ,
# MAGIC kwaeh string ,
# MAGIC kwert_k decimal(22,3),
# MAGIC kfkiv string ,
# MAGIC kmprs string ,
# MAGIC prsqu string ,
# MAGIC txjlv string ,
# MAGIC kbflag string ,
# MAGIC koupd string ,
# MAGIC kmxaw string ,
# MAGIC kmxwr string ,
# MAGIC kawrt_k decimal(22,3),
# MAGIC kunnr string ,
# MAGIC kvarc string ,
# MAGIC varcond string ,
# MAGIC ktrel string ,
# MAGIC mdflg string ,
# MAGIC dataaging string ,
# MAGIC cpf_guid string ,
# MAGIC kaqty decimal(22,3),
# MAGIC val_zero string ,
# MAGIC is_acct_detn_relevant string ,
# MAGIC create_at timestamp,
# MAGIC origin_file string ,
# MAGIC year_month_day string 
# MAGIC )
# MAGIC using delta
# MAGIC partitioned by (YEAR_MONTH_DAY)
# MAGIC LOCATION '/mnt/data_s4/gold/prcd_elements'
# MAGIC     
