-- Databricks notebook source
-- MAGIC %sql
-- MAGIC drop table if exists silver.maestro_centros ;
-- MAGIC create table silver.maestro_centros
-- MAGIC ( 
-- MAGIC cod_centro string COMMENT "Código del centro (almacenamiento/distribución) en S4",
-- MAGIC des_centro	string COMMENT "Código del centro",
-- MAGIC cod_sociedad string COMMENT "Código de sociedad a la que pertenece el centro",
-- MAGIC cod_pais  string COMMENT "Código del país del centro",
-- MAGIC cod_interlocutor_comercial	string COMMENT "Código de interlocutor comercial del centro",
-- MAGIC flg_es_cliente int COMMENT "Flag: Si el material tiene código de cliente (1); caso contrario (0)",
-- MAGIC flg_es_proveedor int COMMENT "Flag: Si el material tiene código de proveedor (1); caso contrario (0)",
-- MAGIC cod_ubigeo string COMMENT "Código ubigeo/código postal del centro",
-- MAGIC des_ciudad string COMMENT "Nombre de la ciudad donde se encuentra el centro",
-- MAGIC des_direccion string COMMENT "Dirección del centro",
-- MAGIC cod_organizacion_compra	string COMMENT "Código de la organización de compra del centro",
-- MAGIC cod_organizacion_venta	string COMMENT "Código de la organización de venta del centro",
-- MAGIC fecha_carga timestamp COMMENT "Fecha y hora de carga de la tabla "
-- MAGIC 
-- MAGIC )
-- MAGIC using delta
-- MAGIC --partitioned by (year_month)
-- MAGIC LOCATION '/mnt/data_entities/silver/maestro_centros'
